version: '3'

services:
    neo4j:
        build: 
          context: ./
          dockerfile: Dockerfile
        networks:
          - neo4j-network
        ports:
          # Not needed if service accessing neo4j is in the same network
          - '7474:7474'
          - '7687:7687' 
          - '9000:22'
        environment:
          - NEO4J_BOLT_PORT_NUMBER=7687
          - NEO4J_HTTP_PORT_NUMBER=7474
          - NEO4J_HTTPS_PORT_NUMBER=7473
          - NEO4J_PASSWORD=neo4j
        volumes:
          - ${PWD}/neo4j_keys/authorized_keys:/root/.ssh/authorized_keys

networks:
  neo4j-network:
    driver: bridge
